### PR TITLE
Add bower.json to allow this package to be installed via bower.

### PR DESCRIPTION
**Pull request by insidewhy**
Could you also `git tag v0.1.0` and then `git push --tags` after merging this PR so that the bower registry can pick it up.

Thank you!

### CODE REVIEW

**Comment by softsimon** [comment]
Done!

**Comment by insidewhy** [comment]
Thanks so much!

**Comment by insidewhy** [comment]
Sorry I forgot a step... could you also run:

```
bower register ui-router-route-to-components git://github.com/softsimon/ui-router-route-to-components
```

from within your source directory. Thanks!

**Comment by softsimon** [comment]
Try now.

**Comment by insidewhy** [comment]
Thanks, that works :+1: Great to get a 4 minute response time when I'm still waiting on some github issues for more than 2 years ;)

**Pull request merged**
